package com.example.chipdip.model

import com.example.chipdip.model.valute.ItemValute
import com.google.gson.annotations.SerializedName

data class Valute(
    @SerializedName("AUD") val aUD: ItemValute,
    @SerializedName("AZN") val aZN: ItemValute,
    @SerializedName("GBP") val gBP: ItemValute,
    @SerializedName("AMD") val aMD: ItemValute,
    @SerializedName("BYN") val bYN: ItemValute,
    @SerializedName("BGN") val bGN: ItemValute,
    @SerializedName("BRL") val bRL: ItemValute,
    @SerializedName("HUF") val hUF: ItemValute,
    @SerializedName("VND") val vND: ItemValute,
    @SerializedName("HKD") val hKD: ItemValute,
    @SerializedName("GEL") val gEL: ItemValute,
    @SerializedName("DKK") val dKK: ItemValute,
    @SerializedName("AED") val aED: ItemValute,
    @SerializedName("USD") val uSD: ItemValute,
    @SerializedName("EUR") val eUR: ItemValute,
    @SerializedName("EGP") val eGP: ItemValute,
    @SerializedName("INR") val iNR: ItemValute,
    @SerializedName("IDR") val iDR: ItemValute,
    @SerializedName("KZT") val kZT: ItemValute,
    @SerializedName("CAD") val cAD: ItemValute,
    @SerializedName("QAR") val qAR: ItemValute,
    @SerializedName("KGS") val kGS: ItemValute,
    @SerializedName("CNY") val cNY: ItemValute,
    @SerializedName("MDL") val mDL: ItemValute,
    @SerializedName("NZD") val nZD: ItemValute,
    @SerializedName("NOK") val nOK: ItemValute,
    @SerializedName("PLN") val pLN: ItemValute,
    @SerializedName("RON") val rON: ItemValute,
    @SerializedName("XDR") val xDR: ItemValute,
    @SerializedName("SGD") val sGD: ItemValute,
    @SerializedName("TJS") val tJS: ItemValute,
    @SerializedName("THB") val tHB: ItemValute,
    @SerializedName("TRY") val tRY: ItemValute,
    @SerializedName("TMT") val tMT: ItemValute,
    @SerializedName("UZS") val uZS: ItemValute,
    @SerializedName("UAH") val uAH: ItemValute,
    @SerializedName("CZK") val cZK: ItemValute,
    @SerializedName("SEK") val sEK: ItemValute,
    @SerializedName("CHF") val cHF: ItemValute,
    @SerializedName("RSD") val rSD: ItemValute,
    @SerializedName("ZAR") val zAR: ItemValute,
    @SerializedName("KRW") val kRW: ItemValute,
    @SerializedName("JPY") val jPY: ItemValute
)
