package com.example.chipdip.model

import com.example.chipdip.model.valute.ItemValute
import com.google.gson.annotations.SerializedName

data class Valute(
    @SerializedName("AUD") val AUD: ItemValute,
    @SerializedName("AZN") val AZN: ItemValute,
    @SerializedName("GBP") val GBP: ItemValute,
    @SerializedName("AMD") val AMD: ItemValute,
    @SerializedName("BYN") val BYN: ItemValute,
    @SerializedName("BGN") val BGN: ItemValute,
    @SerializedName("BRL") val BRL: ItemValute,
    @SerializedName("HUF") val HUF: ItemValute,
    @SerializedName("VND") val VND: ItemValute,
    @SerializedName("HKD") val HKD: ItemValute,
    @SerializedName("GEL") val GEL: ItemValute,
    @SerializedName("DKK") val DKK: ItemValute,
    @SerializedName("AED") val AED: ItemValute,
    @SerializedName("USD") val USD: ItemValute,
    @SerializedName("EUR") val EUR: ItemValute,
    @SerializedName("EGP") val EGP: ItemValute,
    @SerializedName("INR") val INR: ItemValute,
    @SerializedName("IDR") val IDR: ItemValute,
    @SerializedName("KZT") val KZT: ItemValute,
    @SerializedName("CAD") val CAD: ItemValute,
    @SerializedName("QAR") val QAR: ItemValute,
    @SerializedName("KGS") val KGS: ItemValute,
    @SerializedName("CNY") val CNY: ItemValute,
    @SerializedName("MDL") val MDL: ItemValute,
    @SerializedName("NZD") val NZD: ItemValute,
    @SerializedName("NOK") val NOK: ItemValute,
    @SerializedName("PLN") val PLN: ItemValute,
    @SerializedName("RON") val RON: ItemValute,
    @SerializedName("XDR") val XDR: ItemValute,
    @SerializedName("SGD") val SGD: ItemValute,
    @SerializedName("TJS") val TJS: ItemValute,
    @SerializedName("THB") val THB: ItemValute,
    @SerializedName("TRY") val TRY: ItemValute,
    @SerializedName("TMT") val TMT: ItemValute,
    @SerializedName("UZS") val UZS: ItemValute,
    @SerializedName("UAH") val UAH: ItemValute,
    @SerializedName("CZK") val CZK: ItemValute,
    @SerializedName("SEK") val SEK: ItemValute,
    @SerializedName("CHF") val CHF: ItemValute,
    @SerializedName("RSD") val RSD: ItemValute,
    @SerializedName("ZAR") val ZAR: ItemValute,
    @SerializedName("KRW") val KRW: ItemValute,
    @SerializedName("JPY") val JPY: ItemValute
)
